/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Panel;

import com.wahyubagus.project.chatbot.MikaBot;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class pnlBroadcast extends javax.swing.JPanel {

    /**
     * Creates new form pnlBroadcast
     */
    public pnlBroadcast() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaBroadcast = new javax.swing.JTextArea();
        btnKirim = new javax.swing.JButton();

        setForeground(new java.awt.Color(204, 255, 255));

        txtAreaBroadcast.setBackground(new java.awt.Color(255, 255, 255));
        txtAreaBroadcast.setColumns(20);
        txtAreaBroadcast.setForeground(new java.awt.Color(0, 0, 0));
        txtAreaBroadcast.setRows(5);
        jScrollPane1.setViewportView(txtAreaBroadcast);

        btnKirim.setText("Kirim");
        btnKirim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKirimMouseClicked(evt);
            }
        });
        btnKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKirimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
            .addComponent(btnKirim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKirim)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKirimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKirimActionPerformed

    private void btnKirimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKirimMouseClicked
        // TODO add your handling code here:
        MikaBot mikabot = new MikaBot();
        String textBroadcast = txtAreaBroadcast.getText();
        if (mikabot.sendBroadcast(textBroadcast)) {
            JOptionPane.showMessageDialog(null, "Berhasil mengirim broadcast");
            txtAreaBroadcast.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Gagal mengirim broadcast");
        }
    }//GEN-LAST:event_btnKirimMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKirim;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaBroadcast;
    // End of variables declaration//GEN-END:variables
}
